services:
  db:
    image: postgres:15-alpine
    container_name: siksha-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: siksha_db
    ports:
      - "5432:5432"
    volumes:
      - siksha-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: siksha-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@siksha.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  siksha-db-data:
